name: CI with Gradle

on:
  pull_request:
    branches: [ master ]

jobs:
  run-unit-tests:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    env:
      JVM_OPTS: -Xmx3200m
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '9', '10', '11', '12']
        platform: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      env:
        cache-name: cache-dependencies
      with:
        path: ~/.gradle/caches
        key: build-cache-${{ hashFiles('build.gradle') }}
        restore-keys: |
          build-cache-
          build-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Resolve dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: ./gradlew dependencies
    - name: Execute tests
      run: ./gradlew test --debug
